### ISSUE TITLE
[3.X] Maximum age plus one

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#100]
It looks to me that the maximum age is always plus one.

e.g. if the user set 45 as maximum age the list will contain users with the age of 46.

**Comment by modulebaan** [comment]
The age and range filters are an indication as Tinder says. They may send you people outside your range because they want to I guess. This isn't something I can do about it.

**Comment by Nokius** [comment]
yes sounds like a promotion or fill 🤷‍♂️
