### ISSUE TITLE
[3.1] picture arrangement  

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#106]
if the user has 3 pictures the bigger one (left on) gets scaled to fit the position. Which cuts the picture half.

Didn't happen in earlier versions on 3.x branch

**Comment by Nokius** [comment]
happens also with discovery and less then three pictures :s

**Comment by modulebaan** [comment]
I know, I changed it to a GridLayout, it's the intended behavior to fill better the space. If a suser clicks on the image the image if fully displayed.

**Comment by Nokius** [comment]
@modulebaan I expected a wontfix and I understand the change thanks for the feedback :) 

so fare I like 3.1 !!! great work

**Comment by modulebaan** [comment]
I'm glad you like it :)
