### ISSUE TITLE
[3.1] minium age after restart a lowest level

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#115]
It looks like the 3.1 client use the age 18 as minimum age after a restart of the application.

it resets the setup age.

**Comment by modulebaan** [comment]
Wow didn't know that :) Will try to fix that before the release in the Jolla Store :p

**Comment by Nokius** [comment]
I was not able to find the json with setting in the past there was a setting save file to verfiy if it miss to save the correct age range

**Comment by modulebaan** [comment]
it's in profile.json

**Comment by Nokius** [comment]
ah there the is the correct range let me restart sailfinder

**Comment by Nokius** [comment]
the profile.json has the correct age range just the ui shows minimum as 18 which is not correct 

~~~~
    "age_filter_max":29,
    "age_filter_min":24,
~~~

**Comment by modulebaan** [comment]
distance is correct?

**Comment by Nokius** [comment]
distance ?

**Comment by modulebaan** [comment]
Just checked it, all properties are updated except the minimum age.

**Comment by Nokius** [comment]
hmm that odd

**Comment by modulebaan** [comment]
Fixed in V3.1-11
