### ISSUE TITLE
[3.1] About  not updated

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#117]
The users about is not pulled when restarting the application. I used the official client to change come pictures and sailfinder just show less pictures (missing the new once)  

After an adjustment of the age range it pulled all information including the new pictures

**Comment by modulebaan** [comment]
That's true, it uses the cached data when available. When something has been changed, it updates it's cache. I used an experimental function in the past that refreshes the profile data when it's older then X minutes on launch, but that works now OK so I will add it in V3.1-11. Which will be released on Openrepos today in the evening (if I have time).

I made it like this to improve the launch time of Sailfinder and lower the data usage.

**Comment by modulebaan** [comment]
Added in V3.1-12 and released on Openrepos

**Comment by Nokius** [comment]
works well with V3.1-12

**Comment by modulebaan** [comment]
Great! Thanks for reporting it 👍
