### ISSUE TITLE
connecting tinder servers error

### ISSUE THREAD

**Issue by oguzhanssan** [modulebaan/harbour-sailfinder#14]
after facebook login success, tinder server connection problem occurred .. error is below

Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/tinder.py", line 39, in cover
    pyotherside.send('showMainCover', personsURL[0], persons[personsCounterNumberPersons].name, True)

TypeError: 'int' object is not subscriptable

**Comment by modulebaan** [comment]
Thanks for the report, I need to deactivate the cover when the reconnection starts otherwise it requests data that isn't there.

This will be fixed in V1.7
