### ISSUE TITLE
[1.6] scaling of buttons wrong on JollaC

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#15]
The dislike, superlike and like is scaled wrong compared to the Jolla1

![issue_i](https://cloud.githubusercontent.com/assets/879178/16986697/48dc23b2-4e88-11e6-8e58-fb41abc2588e.png)

**Comment by modulebaan** [comment]
Thanks for the report!
I don't have a Jolla C but I will try to fix it :)

**Comment by Nokius** [comment]
I will check it on the Tablet may it happens there too

**Comment by modulebaan** [comment]
Normally, the Tablet should be OK...

**Comment by Nokius** [comment]
yes it's not happening on the Jolla Tablet

**Comment by modulebaan** [comment]
Fixed in V1.8
