### ISSUE TITLE
[1.6 + 2.0] Word wrap space  for Schools field 

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#16]
If the person has more then one School added there is no word wrap / space between the list.

![issue_ii](https://cloud.githubusercontent.com/assets/879178/16986803/de5b903a-4e88-11e6-8baf-f643d1265a2e.png)

**Comment by modulebaan** [comment]
Will be fixed in V1.8

**Comment by Nokius** [comment]
Sorry for reopening, 

In 1.8 it is adding the , if there are more then one School/University.
But if there is only one School it starts with a ,  

## with multiple Schools entries
raw data:
![correct_ii](https://cloud.githubusercontent.com/assets/879178/17457570/031bb0f0-5bfc-11e6-9ad7-a071b7d59c1b.png)
 
viewed:
![correct](https://cloud.githubusercontent.com/assets/879178/17457556/8942fec8-5bfb-11e6-9e71-40378c93f308.png)
 
## with one School 
raw data:
![incorrect_ii](https://cloud.githubusercontent.com/assets/879178/17457577/40c2db86-5bfc-11e6-8736-b8e942fe7be1.png)

viewed:
![incorrect](https://cloud.githubusercontent.com/assets/879178/17457578/47bf057c-5bfc-11e6-9bc6-97f6a1271f0c.png)

**Comment by modulebaan** [comment]
No problem, that's a problem with the Python code... 
For now it will stay like this until I have the new API ready, everything will be decoded then in JSON which is faster and less trouble to fix these small UI issues.

**Comment by modulebaan** [comment]
Fixed in V2.0 for schools, jobs and instagram
