### ISSUE TITLE
Sailfinder won't login to facebook / no remove account option

### ISSUE THREAD

**Issue by Ray-Ven** [modulebaan/harbour-sailfinder#28]
After Sailfinder didn't want to log in to facebook, I removed all sailfinder related files in nemo/.local nemo/.share and nemo/.cache. Sailfinder still won't act like never started before. Is there a way to remove all sailfinder related files, to fresh install the app?
Thank you,
Ray

**Comment by modulebaan** [comment]
I wanted to open Sailfinder today and apparently Tinder blocked the Facebook authentication process which has been around for a couple of years (even before Sailfinder). I'm searching for a solution.

**Comment by Nokius** [comment]
Thanks for the fix =)

**Comment by modulebaan** [comment]
With pleasure :)
