### ISSUE TITLE
[2.0] Crash when opening "People"

### ISSUE THREAD

**Issue by Kaboom22** [modulebaan/harbour-sailfinder#47]
Happens every time reliably.

pyotherside.send() failed handler: file:///usr/share/harbour-sailfinder/qml/pages/PeoplePage.qml:51: TypeError: Cannot read property '_id' of undefined

**Comment by modulebaan** [comment]
Then you have a special person in your matches... Will add a 'try-catch' statement to work around this.

**Comment by modulebaan** [comment]
Fixed in V2.1-1
