### ISSUE TITLE
[2.2]  Recommendations resetted after restart

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#58]
I figured out that there is an issue with Recommendations

If the are enabled `/home/nemo/.config/harbour-sailfinder/settings/settings.json` contains 

> {"instagram": "1", "job": "1", "version": "Sailfinder V2.0", "school": "1", "bio": "1"}

after the some Recommendations got disabled

>  {"instagram": 0.0, "job": 1.0, "version": "Sailfinder V2.0", "school": 1.0, "bio": 1.0}

may this is the issue that after an restart the changes are back to default

**Comment by modulebaan** [comment]
Fixed in V2.3-1
