### ISSUE TITLE
[2.X] Refresh automatically after updating your profile

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#62]
in pre 2.X versions the application refreshed the possible matches after a change of the age range with 2.X it's not doing that. Change applies after the cache get's updated

**Comment by modulebaan** [comment]
There's no signal yet that starts the refresh process when you change your profile settings. Maybe I will add it later.

The previous versions deleted the Mainpage and reloaded it that's why the cache was updated automatically.

**Comment by modulebaan** [comment]
Added in V2.3-1
