### ISSUE TITLE
[2.2] Profile Page crashes when no picture is available 

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#63]
I was able to delete all Pictures I had, after the I was not able to open the Profile page again

I get following error:
`
pyotherside.send() failed handler: file:///usr/share/harbour-sailfinder/qml/pages/ProfilePage.qml:147: TypeError: Cannot read property 'url' of undefined`

**Comment by modulebaan** [comment]
Will be fixed in V2.3-1 It's just a try statement I need to add to avoid this.
