### ISSUE TITLE
[2.2] Don't let the user removes all the pictures

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#64]
I assume to have 0 picture is not option. The official client is not allowing to remove all pictures may sailfinder should also let  one picture at least 

p.s. atm I have no picture dunno may the will ban me :D

**Comment by modulebaan** [comment]
They replace normally your picture with a no image picture. The official client allows this too I think... I will check the official client tomorrow.

**Comment by modulebaan** [comment]
Okay I checked the official client on how they handle this. Will be fixed in V2.3-1
