### ISSUE TITLE
[2.3] Crash just after like

### ISSUE THREAD

**Issue by ThomasBrixLarsen** [modulebaan/harbour-sailfinder#69]
I pressed like and it crashed. I have pressed like many times before without issue.

pyotherside.send() failed handler: file:///usr/share/harbour-sailfinder/qml/pages/MainPage.qml:929: Error: Cannot assign [undefined] to bool

**Comment by modulebaan** [comment]
- After a restart it was OK?
- On which version of Sailfinder are you?

I added a try statement now which should fix this problem in V2.4.

**Comment by ThomasBrixLarsen** [comment]
After restart I had to relogin to facebook, but it worked after that.

Version 2.3 from Jolla Market.

**Comment by modulebaan** [comment]
Thanks! Yes the relogin is normal.
Is fixed in V2.4
