### ISSUE TITLE
Unmatching wrong person

### ISSUE THREAD

**Issue by martininsulander** [modulebaan/harbour-sailfinder#7]
When unmatching (deleting) a person wrong person gets unmatched.

In my case, I had to matches in total. I removed the first one, but the second one was removed.

**Comment by modulebaan** [comment]
I will take a look at it.

**Comment by modulebaan** [comment]
I can't reproduce this problem... I checked also the code and I can't find the problem.

**Comment by martininsulander** [comment]
Thanks for looking at it. I'm pretty sure the problem is there for me.
Previously it just felt as some contacts dissapeared but this time I really
was sure.

If you give me some pointers where to look in the code both in sailfinder
and in pynder, I could try to look at it.

Best Regards from Martin Insulander

2016-05-24 15:02 GMT+02:00 Dylan Van Assche <notifications@github.com>:

**Comment by modulebaan** [comment]
I need to post the code here but for that I need to set up GIT and other stuff... I will try to do this this evening. I have not enough matches to try this out a lot...

**Comment by modulebaan** [comment]
I pushed it :) have fun!

**Comment by modulebaan** [comment]
You should look after deleteMatch and loadMatches, loadNewMatches (lets say every function with Match in) in tinder.py (/qml/pages/)

**Comment by modulebaan** [comment]
I build in V1.6 a safeguard to stop the unmatching if the name doesn't match. It's not a fix.
