### ISSUE TITLE
[2.3] Login FB won't get token when Tinder removed from FB apps

### ISSUE THREAD

**Issue by modulebaan** [modulebaan/harbour-sailfinder#71]
Logging with Facebook after you removed Tinder from your Facebook apps won't work.
Facebook doesn't want to return a token to login.

I'm currently investigating this issue but I don't have a lot of time at the moment. A fix would be available if we can get a long FB token which is very difficult at the moment.
Currently workaround:

- Install Android app version of Tinder via the Amazon App Store (works with Aliendalvik).
- Login into the Tinder Android app
- Tinder is now added to your FB apps again
- Close the Tinder Android app
- Login into Sailfinder

**Comment by modulebaan** [comment]
Hi,

Currently I'm busy with my exams but after that I'm going to develop Sailfinder further. I believe if I change the login process, which I will do then, I can fix all those issues with that fix :)

**Comment by Jbooot** [comment]
Hi,

Thanks for your answer :) Feel free to ask for further details it would be a pleasure to help you improve your app! Good luck for your exams!

**Comment by modulebaan** [comment]
For some reason gives Tinder you a right access token but doesn't allow you to use it...

**Comment by modulebaan** [comment]
@Jbooot 

Well I maybe found a fix from another Tinder API project... I'm not sure it will fix it but I think it will :D
As you can run my app in the Sailfish SDK I think you can also run a Python script in a Python IDE (I use Spyper with Python 2.7)?
In the attachment you can find it, try it and let me know if it works :)
You have to fill in your e-mail & password before you can use it (at the end of the script) and it can take a while before you see anything in the console, if 'OK' appears and a token then you are logged in.
If then a lot of text appears after that it means you can use the API!
[script_login.zip](https://github.com/modulebaan/harbour-sailfinder/files/681164/script_login.zip)

**Comment by Jbooot** [comment]
Well, what I did was more redneck than what you inferred 😄 to have the log above, I just sshed on my phone and ran `harbour-sailfinder`, then made the manipulation on the phone until I had the log messages I wanted.
So here I just intalled the needed python packages on my computer and ran your script in console. It works ! OK appears, then the token, then raw json. So I can use the API! After having ran the script on my desktop, I can now use sailfinder on my jolla.
Thank you very much for this fast fix! Please, don't sacrifice too mutch your study time during exams for single nerds :p

**Comment by modulebaan** [comment]
I'm glad it works!
Bonus: the FB token is a long one for 60 days, in the new version I will use that to fix all the other issues here that are depending on that one. I'm not giving an ETA but you can expect it around the 2nd week of February. 
Thank you for your understanding :+1:, I was on a break and I searched online for other people with the same issue and I found a solution =). I searched for that long token for months but now I finally found it.

BTW: keep in mind that Sailfinder will ditch the Tinder token when it expires, just reuse the script for now :)

**Comment by modulebaan** [comment]
Handled by fixing issue #78 in Sailfinder V3.0
