### ISSUE TITLE
Unable to login.

### ISSUE THREAD

**Issue by CaptainKhan** [modulebaan/harbour-sailfinder#74]
I am getting the following error now:

Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/api.py", line 92, in loginTinder
    if 'token' not in login:

TypeError: argument of type 'bool' is not iterable

**Comment by modulebaan** [comment]
Try again? Let me know if it works now after some time...

I want to change the login process since I found some issues with it but I don't have time for it at the moment...

**Comment by modulebaan** [comment]
Fixed in V2.4
