### ISSUE TITLE
[2.3] Unmatch error and reporting

### ISSUE THREAD

**Issue by CaptainKhan** [modulebaan/harbour-sailfinder#75]
I can unmatch friends but am also consistently receiving the following error:

I also get a network screen with a timer for some reason. After i navigate back the person is gone from people list.

Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/lib/network.py", line 27, in connection
    File = open("NetworkName", 'r') # Read network name

FileNotFoundError: [Errno 2] No such file or directory: 'NetworkName'

**Comment by CaptainKhan** [comment]
FYI: report spam and other option also generates errors.

**Comment by modulebaan** [comment]
Not related to Tinder but the back-on-track system to reestablish a connection.
Thanks for reporting :)

**Comment by modulebaan** [comment]
Will be fixed when V3.0 is released.

**Comment by CaptainKhan** [comment]
ok great thanks modulebaan, by the way i had a feature or improvement idea which would streamline workflow:

Show distance away from you of tinder member you are friends with. Not sure how difficult that would be to incorporate.

**Comment by modulebaan** [comment]
That would be nice but the API doesn't allow that. The API only gives mutual connections.
I haven't discovered the Social API, where you make groups with friends who have Tinder, if it's available there I may add it.
