### ISSUE TITLE
[2.4] Deleting picture results in a Python error

### ISSUE THREAD

**Issue by modulebaan** [modulebaan/harbour-sailfinder#77]
Deleting a picture results in a Python error

**Comment by Paavi20** [comment]
Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/api.py", line 329, in delete_picture
    status_code, pictures = deleteTinder('/media', data)

TypeError: 'NoneType' object is not iterable

**Comment by modulebaan** [comment]
That's indeed the error.
I will fix it in V2.5...
