### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by maidis** [modulebaan/harbour-sailfinder#79]
I translated the application into Turkish. It would be nice if you could add it.

https://dl.dropboxusercontent.com/u/1836567/harbour-sailfinder-tr.ts

**Comment by modulebaan** [comment]
Hi!

Thanks for your effort :+1:  I really appreciate it!
But I'm building right now Sailfinder V3.0 which will has a different UI with different translation strings.
I was going to create a Transifex project where you can contribute to the translation of Sailfinder V3.X. I will let this issue open until the Transifex project has been created.

**Comment by modulebaan** [comment]
Contribute here for Sailfinder V3.X:
https://www.transifex.com/dylanvanassche/harbour-sailfinder/
