### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by CaptainKhan** [modulebaan/harbour-sailfinder#81]
Somehow after installing Defender a DNS blocker i am getting the following login message:

Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/api.py", line 111, in loginTinder
    if 'token' not in login:

TypeError: argument of type 'bool' is not iterable

Other SFOS apps and Android Support app work normally.

Sailfinder 2.4
SFOS 2.0.5.6
Intex Aquafish

Facebook account login and use through Sailfish native browser works and cookies not blocked.

**Comment by CaptainKhan** [comment]
More detailed terminal log. Requires facebook reauthenticate, yes, login, yes, press OK then this:

s",403]
[D] QPythonPriv::formatExc:612 - "PyOtherSide error
: Traceback (most recent call last):

File "/usr/share/harbour-sailfinder/qml/pages/api
.py", line 111, in loginTinder
if 'token' not in login:

TypeError: argument of type 'bool' is not iterable
"
[D] onError:195 - Python ERROR: Return value of PyO
bject call is NULL: Traceback (most recent call las
t):

File "/usr/share/harbour-sailfinder/qml/pages/api
.py", line 111, in loginTinder
if 'token' not in login:

TypeError: argument of type 'bool' is not iterable

**Comment by modulebaan** [comment]
Defender blocks cookies en other stuff, the Requests lib in Sailfinder uses those cookies to maintain a session and when you block that then you can't use it.
