### ISSUE TITLE
Error loading next person

### ISSUE THREAD

**Issue by fanfu** [modulebaan/harbour-sailfinder#9]
Return value of PyObject call is NULL: Traceback (most recent call last):  File "/usr/share/harbour-sailfinder/qml/pages/tinder.py", line 590, in loadAbout    for i in range(len(people[personsCounterNumberPersons].jobs)):IndexError: list index out of rangeDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/share/harbour-sailfinder/qml/pages/tinder.py", line 619, in loadAbout    logFile.write(str(time.asctime(time.localtime(time.time()))) + " [ERROR] Loading about person failed (Unknown Error)\n")UnboundLocalError: local variable 'time' referenced before assignment

**Comment by modulebaan** [comment]
Small bug, will be fixed in the next update.
