### ISSUE TITLE
[3.0] Sailfinder observations so far

### ISSUE THREAD

**Issue by CaptainKhan** [modulebaan/harbour-sailfinder#93]
- [x] 1. when befriended images do not show for friend contact when selected or when roatting phone into landscape like it did before,

- [x] 2. sometimes when writing a message, navigating to new contact and back show no message sent, it disappeared or was never sent and this happens on mobile (crappy) or high speed wifi connection,

- [x] 3. I have had one instance where a notification saud i was out of superlikes but superlikes still showed up and i could click them in the menu in discovery,

- [x] 4. Discovery UI recommendation, cache kast discovered image, fade image move to background and have a larger procesing indicator or spinning wheel,

**Comment by modulebaan** [comment]
1) You mean in matches? You can't see the profile of a user yet, I have a new API where I can pull much more about the user then just the bio and some photos.

2) Is the message there when restarting Sailfinder?

3) Already fixed in V3.1

4) I don't understand what you mean with this? As soon as discovery is started a placeholder shows up.

**Comment by CaptainKhan** [comment]
Hey Dylan, 

1. yes matches, excellent mostly i wanted to scale, zoom and review their account images,
2. The messages do tend to send but i cant see them until much later, i havent figured out what helps, just restarting the app does usually not help. But a day later or so, maybe when logging back into Facebook (tinder?), then they show.
3. excellent.
4. In your previous app version the previous discoveries still showed while it was looking for new discoveries, in a way that was kinda nice to show the last Discovery (image, images) while it is searching for new ones. 
3. 
3.

**Comment by modulebaan** [comment]
1) Maybe in V3.1 but first I nee to fix Sailbook
2) Can you do those actions only and sens me the logs from /home/nemo/.cache/harbour-sailfinder/logging. Best is to check also if you run from a terminal for errors.
4) That was a UI bug not a feature...

**Comment by CaptainKhan** [comment]
1. oki no problem,
2. How can i semd a log file in GitHub blog?
3. yes you are right.

**Comment by modulebaan** [comment]
You can send me an email: dylanXvanXasscheZprotonmailXcom

X=.
Z=@

**Comment by modulebaan** [comment]
1. Just added in V3.1 inclusive caching of the data

**Comment by modulebaan** [comment]
2. Fixed in V3.1
