### ISSUE TITLE
[3.0] Discovery refresh on age or search radius change.

### ISSUE THREAD

**Issue by CaptainKhan** [modulebaan/harbour-sailfinder#96]
Steps to reproduce:
1. adjust age or search radius,
2. navigate to find matches,
3. discovery not active

Work around:
1. close app
2. re-open
3. discovery now running with new matches found

**Comment by CaptainKhan** [comment]
primarily happens when Out of Users flag is set.

**Comment by modulebaan** [comment]
Thanks! I know this 'bug', will be fixed in V3.1

**Comment by modulebaan** [comment]
Fixed in V3.1
