### ISSUE TITLE
[3.X] Gif search shows for s short time another gif

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#98]
When I search I see for short time another gif before it shows the last one. dunno may this is a work-in-progress issue.

**Comment by modulebaan** [comment]
Well I was thinking to change the GIF search thingy since it's difficult to search a GIF and then such glitches can occur.

**Comment by Nokius** [comment]
I was wondering if it's possible to have gif in a line and the user can select via swiping the gif a subtile. (see the attached mock-up)
 
![mock-up](https://cloud.githubusercontent.com/assets/879178/23995239/00c4791c-0a49-11e7-98fa-808739913aaf.jpg)

**Comment by modulebaan** [comment]
Well I wanted to do it like that but I don't know how I can do this in QML with Silica components...

**Comment by Nokius** [comment]
@CODeRUS, @SfietKonstantin anyone of you can help with 'ideas' how @modulebaan could make it. I assume it could be used for later projects as well.

**Comment by modulebaan** [comment]
I already use a SlideshowView but I don't know how to change it to behave it like @Nokius drawed in the comment above.

**Comment by SfietKonstantin** [comment]
I think this is related to how the gifs are loaded: the last gif is loaded first and then the other ones loads.
You should probably use (Silica)ListView to do this. Start first by trying to do something like the photo viewer.

**Comment by modulebaan** [comment]
Thanks! I will try it out with a SilicaListView and let you guys know if it works 👍

**Comment by modulebaan** [comment]
Fixed in V3.1
