### ISSUE TITLE
[3.0] Unmatch mixes the matchesModel

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#99]
After unmatching some matches, the conversation was not attached to the right person. 
A restart fixed the order, looks like that that something got mixed up.

**Comment by modulebaan** [comment]
I thought I fixed this one... Never mind, I will refresh the matches model after an unmatch in the next version :)

**Comment by Nokius** [comment]
will a refresh happen also after a match, atm it's not

**Comment by modulebaan** [comment]
Nope, at the moment Sailfinder lacks this feature.
The reason for this is that I want to use those incremental updates in order to save data and time.
But that will fix a lot of refresh (restarting Sailfinder at the moment does this) thing I guess.

**Comment by Nokius** [comment]
Thanks!

**Comment by modulebaan** [comment]
Fixed in V3.1
